### ISSUE TITLE
awsutils provider errors out with "InternalValidate" at "terraform apply" 

### ISSUE THREAD

**Issue by danielZakai** [cloudposse/terraform-provider-awsutils#16]
I have configured a provider.tf file as such 
`provider "aws" {
  region  = var.region
  profile = "default"
  shared_credentials_file = "~/ec2/SLZ-AWS/.aws/credentials"
}

provider "awsutils" {
  region  = var.region
  profile = "default"
  shared_credentials_file = "~/ec2/SLZ-AWS/.aws/credentials"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.26"
    }
    awsutils = {
      source = "cloudposse/awsutils"
    }
  }
}`

When running "terraform init" the provider is added to the .lock file with no issue. When running "terraform apply", the following error appears:

`Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
        * data source awsutils_ec2_client_vpn_export_client_config:
client_configuration: One of optional, required, or computed must be set`

This provider worked fine (i've been using it extensively) until recently

**Comment by dhess** [comment]
Same here. This appears to have been introduced in `0.6.0`, as `0.5.0` works fine.

**Comment by osterman** [comment]
this will be fixed in `0.7.0` but we're currently having problems with the terraform registry not publishing our releases due to webhook issues.
